# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_emailresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailresponse',
            name='timestamp',
        ),
    ]
