# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_auto_20180320_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='jewelry_type',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='metal',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Steel', 'Steel')], default='Gold', max_length=50),
        ),
    ]
