# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0004_auto_20180320_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jewelry',
            new_name='Metal',
        ),
    ]
