# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0006_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
