# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0007_display_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price of Entire Display'),
        ),
        migrations.AlterField(
            model_name='display',
            name='jewelryset',
            field=models.ManyToManyField(to='jewelry.Metal', verbose_name='Jewelry in Display'),
        ),
    ]
