# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0008_auto_20180529_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Length of Board'),
        ),
        migrations.AddField(
            model_name='display',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Width of Board'),
        ),
    ]
