# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0009_auto_20180529_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='display',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Length of Board (mm.)'),
        ),
        migrations.AlterField(
            model_name='display',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Width of Board (mm.)'),
        ),
    ]
