# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import jewelry.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0010_auto_20180530_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='image',
            field=models.ImageField(null=True, upload_to=jewelry.models.upload_metal),
        ),
    ]
