# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-02 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0011_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactLense',
        ),
    ]
