# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0012_auto_20180602_2300'),
        ('jewelry', '0011_metal_image'),
    ]

    operations = [
    ]
