# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0013_merge_20180603_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metal',
            name='jewelry_type',
            field=models.CharField(max_length=50, verbose_name='Type of Jewelry'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='metal',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Steel', 'Steel')], default='Gold', max_length=50, verbose_name='Type of Metals'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size (mm.)'),
        ),
    ]
