# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0014_auto_20180606_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlense',
            options={'verbose_name': 'Contact Lense', 'verbose_name_plural': 'Contact Lenses'},
        ),
        migrations.AlterField(
            model_name='contactlense',
            name='color',
            field=models.CharField(choices=[('PURPLE', 'PURPLE'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('RED', 'RED')], default='RED', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='contactlense',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='contactlense',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size (mm.)'),
        ),
    ]
