# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0016_auto_20180609_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlense',
            name='color',
            field=models.CharField(choices=[('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red')], default='Red', max_length=50, verbose_name='Color'),
        ),
    ]
