# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import jewelry.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0017_auto_20180609_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlense',
            name='image',
            field=models.ImageField(null=True, upload_to=jewelry.models.upload_lense),
        ),
    ]
