# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0018_contactlense_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='image',
            field=models.ImageField(null=True, upload_to='display/'),
        ),
    ]
