# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0021_auto_20180613_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='full_price',
            field=models.IntegerField(default=0, verbose_name='Price of Entire Display'),
        ),
        migrations.AlterField(
            model_name='display',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Length of Board (mm.)'),
        ),
    ]
