# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0024_auto_20180614_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display',
            options={'verbose_name': 'Display', 'verbose_name_plural': 'Displays'},
        ),
    ]
