# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0026_auto_20180614_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlense',
            old_name='timestampe',
            new_name='timestamp',
        ),
    ]
