# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0027_auto_20180614_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='name',
            field=models.CharField(default='Name of Display', max_length=50),
        ),
    ]
