# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0029_auto_20180615_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_type', models.CharField(max_length=25, verbose_name='J Type')),
            ],
        ),
        migrations.CreateModel(
            name='TestA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberA', models.IntegerField(default=0, verbose_name='Number A')),
            ],
        ),
        migrations.CreateModel(
            name='TestB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberB', models.IntegerField(default=0, verbose_name='Number B')),
            ],
        ),
    ]
