# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0029_auto_20180615_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlense',
            old_name='color',
            new_name='jewelry_style',
        ),
        migrations.RenameField(
            model_name='metal',
            old_name='metal',
            new_name='jewelry_style',
        ),
    ]
