# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0030_auto_20180812_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price of Entire Display'),
        ),
    ]
