# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0030_mastertest_testa_testb'),
    ]

    operations = [
        migrations.AddField(
            model_name='testa',
            name='MasterTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelry.MasterTest'),
        ),
    ]
