# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0031_testa_mastertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testb',
            name='MasterTest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jewelry.MasterTest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testa',
            name='MasterTest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jewelry.MasterTest'),
            preserve_default=False,
        ),
    ]
