# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0031_auto_20180818_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display',
            old_name='jewelryset',
            new_name='metal_set',
        ),
    ]
