# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0032_auto_20180730_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testa',
            name='MasterTest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jewelry.MasterTest'),
        ),
        migrations.AlterField(
            model_name='testb',
            name='MasterTest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jewelry.MasterTest'),
        ),
    ]
