# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0032_auto_20180818_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='metal_set',
            field=models.ManyToManyField(to='jewelry.Metal', verbose_name='Earring, Nose Hook, BraceletIn Display'),
        ),
    ]
