# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0034_auto_20180818_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='contactLense_set',
            field=models.ManyToManyField(to='jewelry.ContactLense', verbose_name='Contact Lense In Display'),
        ),
    ]
