# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0035_display_contactlense_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='contactLense_set',
            field=models.ManyToManyField(to='jewelry.ContactLense', verbose_name='Contact Lenses In Display'),
        ),
        migrations.AlterField(
            model_name='display',
            name='metal_set',
            field=models.ManyToManyField(to='jewelry.Metal', verbose_name='Earrings, Nose Hooks, Bracelets In Display'),
        ),
    ]
