# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0039_auto_20180819_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Width of Board (mm.)'),
        ),
    ]
